spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gmall2?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: python123

server:
  port: 8090